# Generated by Django 3.1.2 on 2020-10-18 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='code_number',
            field=models.IntegerField(choices=[('CHL +56', 56), ('ARG +56', 2), ('BRZ +56', 3), ('USA', 4), ('COL', 5)], default=0, max_length=12),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='points',
            field=models.IntegerField(default=0),
        ),
    ]
