# Generated by Django 3.1.2 on 2020-10-18 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20201018_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='code_number',
            field=models.IntegerField(choices=[(56, 'CHL +56'), (23, 'ARG +56'), (23, 'BRZ +56'), (1, 'USA 1'), (634, 'COL')], default=0, max_length=12),
        ),
    ]
