# Generated by Django 3.1.2 on 2020-10-18 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20201018_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilevote',
            name='vote',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], max_length=1),
        ),
    ]
