# Generated by Django 3.1.2 on 2020-10-19 21:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20201018_1534'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='dateBirth',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='code_number',
            field=models.IntegerField(choices=[(56, 'CHL +56'), (54, 'ARG +54'), (55, 'BRZ +55'), (1, 'USA +1'), (57, 'COL +57')], default=0, max_length=12),
        ),
    ]
