# Generated by Django 3.1.2 on 2020-11-02 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20201019_1844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='code_number',
            field=models.IntegerField(choices=[(56, 'CHL +56'), (54, 'ARG +54'), (55, 'BRZ +55'), (1, 'USA +1'), (57, 'COL +57')], default=0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='default.png', upload_to='profile_pics'),
        ),
        migrations.AlterField(
            model_name='profilevote',
            name='vote',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')]),
        ),
    ]
