# Generated by Django 3.1.2 on 2020-11-03 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20201102_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='dateBirth',
            field=models.DateField(default=0),
        ),
    ]
