# Generated by Django 3.1.2 on 2020-10-21 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_post_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='price',
            new_name='base_price',
        ),
    ]
